[package]
name = "grease-bin"
version = "0.1.0"
authors = ["Kent Fredric <kentnl@gentoo.org>"]
edition = "2018"

[dependencies]
grease = { path = "../grease" }

[dependencies.clap]
version = "~2.32"
default-features = false

features = ["suggestions", "color", "vec_map"]
